######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 9 17:57:15 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    mainpanal.cpp \
    devicebutton.cpp \
    nodedetail.cpp

HEADERS += \
    mainpanal.h \
    devicebutton.h \
    nodedetail.h

RESOURCES += \
    res.qrc
